version: '3'

services:
  rpa_user_provider:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.user
    image: rpa_user_provider
    volumes:
      - ./user:/go/src/github.com/synerex/provider/provider_rpa/user
    ports:
      - "8888:8888"
    networks:
      - synerex_net
      - default
  meeting_provider:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.meeting
    image: meeting_provider
    volumes:
      - .:/go/src/github.com/synerex/provider/provider_rpa/meeting
    networks:
      - synerex_net
      - default
networks:
  synerex_net:
    external: true